### ISSUE TITLE
SpecklePoints[] instead of double[]?

### ISSUE THREAD

**Issue by Eckart-S** [speckleworks/SpeckleCore#65]
Wouldn't it make sense to use SpecklePoints instead of double[] Points { get; set; } for Curves etc.?
Name "Points" might be misleading as it's in reality Point coordinates and not SpecklePoints.

**Comment by didimitrie** [comment]
it would be good dev-experience wise, but what if i would  add a default extension for arrays that you would just call .ToPoints on an array? `Points[] fromArray( array )` ? 

I'm  insisting on this because once you make a speckle  object, in theory it should get a hash, _id, etc. that will increase a lot the transport size

**Comment by didimitrie** [comment]
i'm going to close this as it's not happening in 1.x.x
